### PR TITLE
Remove blood frame from BM (reinvented in magic bees)

### PR DESCRIPTION
**Pull request by chochem**
fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13178

### CODE REVIEW

**Comment by Connor-Colenso** [comment]
I mean at this point might make sense to just yeet the item entirely?

**Comment by Alastors** [comment]
> I mean at this point might make sense to just yeet the item entirely?

nah gimme a bit, I'll fix it I guess

**Comment by Dream-Master** [comment]
I hate it much if everything is removed. Why we not fixt it? It might be a wrong recipe I add via script or so

**Comment by chochem** [comment]
the recipe is right here. looks like the item is the problem not the recipe. anyway close now, colen gave alastor a week to fix it. :P

**Comment by chochem** [comment]
why reopened?

**Comment by Connor-Colenso** [comment]
> why reopened?

This item is getting removed from BM and added to Magic Bees, I have asked Alastor to change this PR to actually remove the item as well as disable the recipe so we can move it over properly.

**Comment by Alastors** [comment]
https://github.com/GTNewHorizons/MagicBees/pull/20 This item has officially been deleted from Blood Magic and re-added through Magic Bees

**Review by Dream-Master — APPROVED** [review]

**Pull request merged**
