### PR TITLE
Add suport of using the GT miners to mine the ores from the BloodMagic ritual "Mark of the Falling Tower"

### PR DESCRIPTION
**Pull request by MuXiu1997**
Closed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10176
@Kiwi233  helped test

### CODE REVIEW

**Review by kubasz — CHANGES_REQUESTED** [review]
You need to also add a dependency on gt5u to the `@Mod` annotation if you're adding it to gradle+java, something like "required-after:gregtech;"

**Comment by miozune** [comment]
Check if GT is loaded would be preferred, rather than adding complete dependency.

**Comment by MuXiu1997** [comment]
> Check if GT is loaded would be preferred, rather than adding complete dependency.

I'm doing it.

**Comment by kubasz** [comment]
> I'm doing it.

You're not, if you import a class and use it in instanceof, and the mod is missing, you'll get a JVM error afaik. You either have to conditionally load a whole class file, or use reflection to avoid errors with missing mods

**Comment by kubasz** [comment]
This looks good, just also add gregtech as an `after` dependency to the @Mod annotation to make sure BM loads after GT if it's present

**Comment by MuXiu1997** [comment]
idk, Does `FMLPostInitializationEvent` also need `after dependency`?

**Comment by kubasz** [comment]
> idk, Does `FMLPostInitializationEvent` also need `after dependency`?

I don't think so

**Comment by glowredman** [comment]
@MuXiu1997 have you tried if this crashes in an environment without GT? I've only seen `@Optional.Method` together with `@Optional.Interface`, so I'm not sure if FML considers this method for removal.

**Comment by MuXiu1997** [comment]
@glowredman 
No
But here's an example that I referenced herehttps://github.com/GTNewHorizons/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/block/BlockTeleposer.java#L275

**Comment by glowredman** [comment]
Alright, good to know.

**Review by glowredman — APPROVED** [review]

**Review by kubasz — APPROVED** [review]
I guess because it's only checked in postInit, gregtech will already be preinited and inited by this stage, so it should work without the dependency

**Pull request merged**
