### PR TITLE
Add new rune to reduce the delay between crafts

### PR DESCRIPTION
**Pull request by C0bra5**
This PR aims to add a rune to reduce the delay between consecutive altar crafts.

The new rune is called the `Quickness Rune`. It multiplicatively reduces the maximum delay between consecutive crafts by 20%. You'll need about 20 runes to reach the minimum delay of 1 world tick tick. Previously, World Accelerators didn't affect the frequency at which the altar checks if it can start a recipe. I've kept this behaviour, meaning players can't get around this mechanic with a world accelerator. I do want to make the final recipe require an accelerator of some kind.

This PR also addresses some issues with the altar:
- Since the altar used the world time and not the world age, some mechanics were impossible to trigger if you set doDaylightCycle to false.
- For example, it was only possible to start a craft if the time was set to a multiple of 100.

If this PR is accepted, additional work will need to be completed to get the rune ready for use in the pack:
- Update the portable altar from Blood Arsenal to support the new rune.
- Add a Thaumonomicon entry and a balanced recipe for the new rune in the core mod.
  - BM has lang files for a guidebook. I have no clue how to access the guidebook in the game, but I've added an entry anyway. That entry can be reused for the thaumonomicon entry.
- The GTNH quests for T5 runes will need to be updated since the quickness rune is a T5 rune (that or whatever tier we end up deciding on)
- Additional language entries must be added since I only speak French and English.

Here is an example of the rune in action:
https://github.com/GTNewHorizons/BloodMagic/assets/17766417/002a44b6-825d-4649-9ab6-03ef1393ce3b

### CODE REVIEW

**Review by Alastors — APPROVED** [review]
Looks good to me

**Comment by Dream-Master** [comment]
@C0bra5 can you add a recipe in core mod so the rune get a propper gtnh recipe ?

**Comment by C0bra5** [comment]
> @C0bra5 can you add a recipe in core mod so the rune get a propper gtnh recipe ?

can do

**Review by Dream-Master — CHANGES_REQUESTED** [review]
@C0bra5 i will merge and tag it when the core mod recipe is added

**Review by Dream-Master — APPROVED** [review]

**Comment by RaidhoSketch** [comment]
The guidebook entry is currently not properly localized, but it can be fixed by updating the en_US.lang file in the alchemicalwizardryBooks asset folder with **these** lines:

aw.entries.architect.quicknessRune=Ever since I automated the transmutation process, I've noticed that the altar always waits a certain amount of time before starting a new transmutation. This odd delay doesn't occur when I manually insert the items into the altar, but that seems counterproductive to my goal of automation. I tried reducing the delay by causing time anomalies around the altar. While this affected the transmutation speed, it did not affect the delay. After much trial and error, I found that I could reduce this trivial delay by using a new type of rune made from speed and acceleration runes. Every rune I add to the altar seems to reduce the delay by about 20%. The effect is multiplicative and not additive.

guide.BloodMagic.entryName.architect.quicknessRune=The Quickness Runes

**Comment by Shahelion** [comment]
> The guidebook entry is currently not properly localized, but it can be fixed by updating the en_US.lang file in the alchemicalwizardryBooks asset folder with **these** lines:
> 
> aw.entries.architect.quicknessRune=Ever since I automated the transmutation process, I've noticed that the altar always waits a certain amount of time before starting a new transmutation. This odd delay doesn't occur when I manually insert the items into the altar, but that seems counterproductive to my goal of automation. I tried reducing the delay by causing time anomalies around the altar. While this affected the transmutation speed, it did not affect the delay. After much trial and error, I found that I could reduce this trivial delay by using a new type of rune made from speed and acceleration runes. Every rune I add to the altar seems to reduce the delay by about 20%. The effect is multiplicative and not additive.
> 
> guide.BloodMagic.entryName.architect.quicknessRune=The Quickness Runes

For some reason, this no longer works.

**Pull request merged**
