### PR TITLE
Added my own changes to the meteor stuff

### PR DESCRIPTION
**Pull request by Prometheus0000**
Note that the cfg file name has changed to Blood Magic.cfg, so you can tell what it is easier.

See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6871 for more details.

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Prometheus0000 are this old code ? if yes please close it or remove the draft tag

**Comment by Prometheus0000** [comment]
Old code? Why would you think that? I was working on other stuff when I was waiting for the meteor PR to be ready to be merged, and this combines with it. Did you not read https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6871?

It would be nice if someone actually looked at the code though.

**Comment by Dream-Master** [comment]
I can push it to zeta to Test ?

**Comment by Prometheus0000** [comment]
No. It's missing the blood orbs for T7-9, which is what I wanted feedback on. Since there are mods that add other ones. I wrote about all this in the issue?

**Comment by Dream-Master** [comment]
@Prometheus0000 @ScriptedPiky can we close this ?

**Comment by boubou19** [comment]
won't be continued

**Pull request closed without merging**
